version: "3.8"
services:

    # nginx
    nginx-service:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        container_name: p5-webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./project:/var/www
            - ./project/storage/logs/nginx:/var/log/nginx:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker/nginx/conf.d/gzip.conf:/etc/nginx/conf.d/gzip.conf:cached
            - ./docker/nginx/certs:/etc/ssl/certs:cached
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached
            - ./docker/nginx/snippets:/etc/nginx/snippets:cached
            - ./docker/nginx/templates:/etc/nginx/templates:cached
        env_file:
            - .nginx.env
        depends_on:
            - app-service
            - mariadb-service
        networks:
            - backend

    # php
    app-service:
        build:
            context: docker
            dockerfile: php/Dockerfile
        container_name: p5-app
        environment:
            XDEBUG_IDEKEY: PHPSTORM
            XDEBUG_REMOTE_PORT: 9003 # https://xdebug.org/docs/upgrade_guide#Step-Debugging
            XDEBUG_REMOTE_HOST: host.docker.internal
        ports:
            - "9000:9000"
            - "8000:8000"
        volumes:
            - ./project:/var/www
            - ~/composer:/root/.composer
        networks:
            - backend

    # database (mariadb)
    mariadb-service:
        image: mariadb:latest
        container_name: p5-mariadb
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql/cnf:/etc/mysql/conf.d
            - ./docker/mysql/database:/var/lib/mysql
            - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
        env_file:
            - .sql.env
        networks:
            - backend

networks:
    backend:
